services:
  cypress:
    image: cypress/included:13.6.0
    working_dir: /e2e
    volumes:
      - ./deploy/cypress:/e2e
      - ./deploy/cypress/node_modules:/e2e/node_modules
    environment:
      CYPRESS_BASE_URL: http://proxy
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
    networks:
      - local_net
