services:
  cypress:
    build:
      context: .
      dockerfile: deploy/tools/docker/cypress/Dockerfile
    environment:
      CYPRESS_BASE_URL: http://proxy
    volumes:
      - ./deploy/cypress:/e2e:cached
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
    networks:
      - local_net
