// Dummy events to test react-big-calendar
// Fields: id, title, start, end, allDay, type, user, color, status

const now = new Date();
const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 9, 0, 0);

export type SampleEvent = {
  id: string;
  title: string;
  start: string | Date;
  end: string | Date;
  allDay?: boolean;
  type?: 'vacation' | 'sick' | 'personal' | 'remote';
  status?: 'approved' | 'pending' | 'declined';
  user?: string;
  color?: string;
};

export const sampleEvents: SampleEvent[] = [
  {
    id: '1',
    title: 'Vacation — John Doe',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 1, 0, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 4, 23, 59, 59),
    allDay: true,
    type: 'vacation',
    user: 'John Doe',
    color: '#1E88E5',
    status: 'approved',
  },
  {
    id: '2',
    title: 'Sick — Ana Petrović',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 2, 10, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 2, 16, 0, 0),
    allDay: false,
    type: 'sick',
    user: 'Ana Petrović',
    color: '#FF7043',
    status: 'pending',
  },
  {
    id: '3',
    title: 'Remote — Marko',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 5, 9, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 5, 17, 0, 0),
    allDay: false,
    type: 'remote',
    user: 'Marko',
    color: '#62BEAC',
    status: 'approved',
  },
  {
    id: '4',
    title: 'Personal — Ivana',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() - 3, 0, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() - 2, 23, 59, 59),
    allDay: true,
    type: 'personal',
    user: 'Ivana',
    color: '#9C27B0',
    status: 'approved',
  },
  {
    id: '5',
    title: 'Vacation — Team overlap',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 0, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 6, 23, 59, 59),
    allDay: true,
    type: 'vacation',
    user: 'Multiple',
    color: '#1E88E5',
    status: 'pending',
  },
  {
    id: '6',
    title: 'Half-day — Milan (AM)',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 1, 9, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 1, 12, 0, 0),
    allDay: false,
    type: 'personal',
    user: 'Milan',
    color: '#FFA726',
    status: 'approved',
  },
  {
    id: '7',
    title: 'Workshop — Petra',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 2, 9, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 17, 0, 0),
    allDay: false,
    type: 'remote',
    user: 'Petra',
    color: '#29B6F6',
    status: 'approved',
  },
  {
    id: '7',
    title: 'Workshop — es',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 2, 9, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 17, 0, 0),
    allDay: false,
    type: 'remote',
    user: 'Petra',
    color: '#29B6F6',
    status: 'approved',
  },
  {
    id: '8',
    title: 'Sick — Luka',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 4, 0, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 4, 23, 59, 59),
    allDay: true,
    type: 'sick',
    user: 'Luka',
    color: '#D32F2F',
    status: 'pending',
  },
  {
    id: '9',
    title: 'Vacation — Dragan',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 7, 0, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 14, 23, 59, 59),
    allDay: true,
    type: 'vacation',
    user: 'Dragan',
    color: '#7E57C2',
    status: 'approved',
  },
  {
    id: '10',
    title: 'Remote — Sara',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 5, 13, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 5, 18, 0, 0),
    allDay: false,
    type: 'remote',
    user: 'Sara',
    color: '#26A69A',
    status: 'approved',
  },
  {
    id: '11',
    title: 'Personal — Ana (Afternoon)',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() - 1, 14, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() - 1, 17, 0, 0),
    allDay: false,
    type: 'personal',
    user: 'Ana',
    color: '#EC407A',
    status: 'approved',
  },
  {
    id: '12',
    title: 'Half-day — Vesna (PM)',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 13, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 17, 0, 0),
    allDay: false,
    type: 'personal',
    user: 'Vesna',
    color: '#FFD54F',
    status: 'pending',
  },
  {
    id: '13',
    title: 'Conference — All Hands',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 10, 0, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 12, 23, 59, 59),
    allDay: true,
    type: 'vacation',
    user: 'Company',
    color: '#5C6BC0',
    status: 'approved',
  },
  {
    id: '14',
    title: 'Onboarding — New Hire',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 2, 9, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 2, 17, 0, 0),
    allDay: false,
    type: 'personal',
    user: 'New Hire',
    color: '#42A5F5',
    status: 'approved',
  },
  {
    id: '15',
    title: 'National Holiday',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 20, 0, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 20, 23, 59, 59),
    allDay: true,
    type: 'personal',
    user: 'Public',
    color: '#8BC34A',
    status: 'approved',
  },
  // Additional overlapping requests for testing vertical scroll in month cells
  {
    id: '16',
    title: 'Vacation — Nikola',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 0, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 23, 59, 59),
    allDay: true,
    type: 'vacation',
    user: 'Nikola',
    color: '#1976D2',
    status: 'approved',
  },
  {
    id: '17',
    title: 'Sick — Jelena',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 0, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 23, 59, 59),
    allDay: true,
    type: 'sick',
    user: 'Jelena',
    color: '#E53935',
    status: 'approved',
  },
  {
    id: '18',
    title: 'Remote — Stefan',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 9, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 17, 0, 0),
    allDay: false,
    type: 'remote',
    user: 'Stefan',
    color: '#00897B',
    status: 'pending',
  },
  {
    id: '19',
    title: 'Personal — Maja',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 10, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 15, 0, 0),
    allDay: false,
    type: 'personal',
    user: 'Maja',
    color: '#AB47BC',
    status: 'approved',
  },
  {
    id: '20',
    title: 'Vacation — Igor',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 0, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 5, 23, 59, 59),
    allDay: true,
    type: 'vacation',
    user: 'Igor',
    color: '#5E35B1',
    status: 'approved',
  },
  {
    id: '21',
    title: 'Sick — Tamara',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 0, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 23, 59, 59),
    allDay: true,
    type: 'sick',
    user: 'Tamara',
    color: '#C62828',
    status: 'pending',
  },
  {
    id: '22',
    title: 'Remote — Dušan',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 11, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 16, 0, 0),
    allDay: false,
    type: 'remote',
    user: 'Dušan',
    color: '#00ACC1',
    status: 'approved',
  },
  {
    id: '23',
    title: 'Personal — Ivana M.',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 0, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 23, 59, 59),
    allDay: true,
    type: 'personal',
    user: 'Ivana M.',
    color: '#8E24AA',
    status: 'approved',
  },
  {
    id: '24',
    title: 'Remote — Petar (late)',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 18, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 22, 0, 0),
    allDay: false,
    type: 'remote',
    user: 'Petar',
    color: '#0288D1',
    status: 'approved',
  },
  {
    id: '25',
    title: 'Sick — Andrej',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 0, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 23, 59, 59),
    allDay: true,
    type: 'sick',
    user: 'Andrej',
    color: '#D84315',
    status: 'approved',
  },
  {
    id: '26',
    title: 'Personal — Ksenija',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 9, 30, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 11, 30, 0),
    allDay: false,
    type: 'personal',
    user: 'Ksenija',
    color: '#7B1FA2',
    status: 'pending',
  },
  {
    id: '27',
    title: 'Vacation — Zoran',
    start: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 3, 0, 0, 0),
    end: new Date(startOfToday.getFullYear(), startOfToday.getMonth(), startOfToday.getDate() + 4, 23, 59, 59),
    allDay: true,
    type: 'vacation',
    user: 'Zoran',
    color: '#3949AB',
    status: 'approved',
  },
];

export default sampleEvents;
